mysite/main/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('', views.index, name='index'), 
    path('user_page/', views.user_page, name='user_page'), 
    path('login/', views.login_request, name='login'),
    path('register/',views.register_request, name='register'),
    path('logout', views.logout_request, name='logout')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UploadFile(models.Model):

    page_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_file')
    file = models.FileField('File')

mysite/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UploadFile


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
	

class UploadForm(forms.ModelForm):
	class Meta:
		model = UploadFile
		fields = ['page_user', 'file']

mysite/main/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm, UploadForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from .models import UploadFile
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    return render(request, 'main/index.html', context={

    })

def user_page(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = UploadForm()
    file_list = UploadFile.objects.all()
    return render(request, 'main/user_page.html', context={
	    'form':form,
	    'file_list':file_list
    })


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("index")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render(request=request, template_name="main/register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("index")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("index")

mysite/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <h1>{% block name %}{% endblock %}</h1>
        <div>
            <a href="{% url 'index' %}"><button>Home</button></a>
            <a href="{% url 'user_page' %}"><button>User page</button></a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><button>{{ user.username }} Logout</button></a>
            {% else %}
                <a href="{% url 'login' %}"><button>Login</button></a>
                <a href="{% url 'register' %}"><button>Register</button></a>
            {% endif %}
        </div>
    </header>
    {% block content %}{% endblock %}
    

</body>
</html>

mysite/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Converter{% endblock %}


{% block name %}Converter{% endblock %}

{% block content %}{% endblock %}

mysite/main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}Login{% endblock %}


{% block name %}Login{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <button type="submit">Login</button>
    </form>

{% endblock %}

mysite/main/templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}Register{% endblock %}


{% block name %}Register{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ register_form.as_p }}
        <button type="submit">Register</button>
    </form>

{% endblock %}

mysite/main/templates/main/user_page.html
{% extends 'main/base.html' %}

{% block title %}User page{% endblock %}


{% block name %}User page{% endblock %}

{% block content %}
    <h4>{{ user.username }}</h4>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <label  for="id_page_user"></label>
            <select hidden name="page_user" required="" id="id_page_user">
          <option hidden value="{{ user.id }}"></option>
        </select>
          </p>
        <input type="file" name="file" id="">
        <button type="submit">Upload</button>
    </form>

    <div>
        {% for i in file_list %}
            {% if i.page_user == user %}
                <p>{{ i.file }}</p>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}